export enum IconNameEnum {
  AccountLogo = 'AccountLogo',
  Activity = 'Activity',
  Add = 'Add',
  AddChain = 'AddChain',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  Assets = 'Assets',
  CheckDone = 'CheckDone',
  CheckEmpty = 'CheckEmpty',
  Copy = 'Copy',
  Dropdown = 'Dropdown',
  Dropup = 'Dropup',
  Edit = 'Edit',
  EyeClosed = 'EyeClosed',
  EyeOpen = 'EyeOpen',
  Gas = 'Gas',
  Loaders = 'Loaders',
  Nft = 'Nft',
  Out = 'Out',
  Partners = 'Partners',
  Qrscan = 'Qrscan',
  Receive = 'Receive',
  Search = 'Search',
  Send = 'Send',
  Settings = 'Settings',
  Stake = 'Stake',
  Swap = 'Swap',
  Topup = 'Topup',
  X = 'X',
  // networks
  Klaytn = 'Klaytn',
  Ethereum = 'Ethereum',
  BinanceSmartChain = 'BinanceSmartChain',
  NetworkFallback = 'NetworkFallback',
  Qrcode = 'Qrcode',
  Slider = 'Slider'
}
