name: Secrets setup

description: Writes secrets

runs:
  using: 'composite'
  steps:
    - name: Create apps/extension-e2e/.env file
      shell: bash
      run: |
        cat << EOF > apps/extension-e2e/.env
        DEFAULT_SEED_PHRASE=${{ inputs.DEFAULT_SEED_PHRASE }}
        DEFAULT_PASSWORD=${{ inputs.DEFAULT_PASSWORD }}
        DEFAULT_HD_ACCOUNT_PRIVATE_KEY=${{ inputs.DEFAULT_HD_ACCOUNT_PRIVATE_KEY }}
        EOF

    - name: Create apps/extension/.env file
      shell: bash
      run: |
        cat << EOF > apps/extension/.env
        BACKEND_URL=${{ inputs.BACKEND_URL }}
        EOF

    - name: Create apps/mobile/.env file
      shell: bash
      run: |
        cat << EOF > apps/mobile/.env
        BACKEND_URL=${{ inputs.BACKEND_URL }}
        EOF
