name: Secrets setup

description: Writes secrets

inputs:
  BACKEND_URL:
    description: "Backend API url"
    required: true
  DEFAULT_HD_ACCOUNT_SEED_PHRASE:
    description: "Seed phrase for E2E tests"
    required: false
  DEFAULT_PASSWORD:
    description: "Wallet password for E2E tests"
    required: false
  DEFAULT_HD_ACCOUNT_FIRST_PRIVATE_KEY:
    description: "First account private key for E2E tests"
    required: false
  SEED_PHRASE_FOR_IMPORT:
    description: "Seed phrase for account import for E2E tests"
    required: false
  IMPORTED_BY_SEED_PRIVATE_KEY:
    description: "Private key for account imported by seed for E2E tests"
    required: false
  IMPORTED_BY_SEED_PUBLIC_KEY:
    description: "Public key for account imported by seed for E2E tests"
    required: false
  IMPORTED_BY_PRIVATE_KEY_PRIVATE_KEY:
    description: "Private key for account import for E2E tests"
    required: false
  IMPORTED_BY_PRIVATE_KEY_PUBLIC_KEY:
  description: "Public key for account imported by private key for E2E tests"
  required: false

runs:
  using: 'composite'
  steps:
    - name: Create apps/extension-e2e/.env file
      shell: bash
      run: |
        cat << EOF > apps/extension-e2e/.env
        DEFAULT_HD_ACCOUNT_SEED_PHRASE=${{ inputs.DEFAULT_HD_ACCOUNT_SEED_PHRASE }}
        DEFAULT_PASSWORD=${{ inputs.DEFAULT_PASSWORD }}
        DEFAULT_HD_ACCOUNT_FIRST_PRIVATE_KEY=${{ inputs.DEFAULT_HD_ACCOUNT_FIRST_PRIVATE_KEY }}
        SEED_PHRASE_FOR_IMPORT=${{ inputs.SEED_PHRASE_FOR_IMPORT }}
        IMPORTED_BY_PRIVATE_KEY_PRIVATE_KEY=${{ inputs.IMPORTED_BY_PRIVATE_KEY_PRIVATE_KEY }}
        IMPORTED_BY_PRIVATE_KEY_PUBLIC_KEY=${{ inputs.IMPORTED_BY_PRIVATE_KEY_PUBLIC_KEY }}
        IMPORTED_BY_SEED_PRIVATE_KEY=${{ inputs.IMPORTED_BY_SEED_PRIVATE_KEY }}
        IMPORTED_BY_SEED_PUBLIC_KEY=${{ inputs.IMPORTED_BY_SEED_PUBLIC_KEY }}
        EOF

    - name: Create apps/extension/.env file
      shell: bash
      run: |
        cat << EOF > apps/extension/.env
        BACKEND_URL=${{ inputs.BACKEND_URL }}
        EOF

    - name: Create apps/mobile/.env file
      shell: bash
      run: |
        cat << EOF > apps/mobile/.env
        BACKEND_URL=${{ inputs.BACKEND_URL }}
        EOF
