/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Erc165Abi, Erc165AbiInterface } from "../Erc165Abi";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Erc165Abi__factory {
  static readonly abi = _abi;
  static createInterface(): Erc165AbiInterface {
    return new utils.Interface(_abi) as Erc165AbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Erc165Abi {
    return new Contract(address, _abi, signerOrProvider) as Erc165Abi;
  }
}
