/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Erc20Abi__factory } from "./Erc20Abi__factory";
export { Erc721abi__factory } from "./Erc721abi__factory";
