export const MAX_PASSWORD_ATTEMPTS = 3;
export const WRONG_PASSWORD_LOCK_TIME = 60 * 1000;
export const INITIAL_ENTER_WRONG_PASSWORD_ATTEMPTS = 0;
export const INITIAL_ENTER_PASSWORD_LOCK_TIME = 0;
export const DELAY_TIME = 5000;
