name: Code quality

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  code-quality:
    name: Checks if ts, lint, unit tests works & create build
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Environment setup
        uses: ./.github/workflows/environment-setup

      - name: Install dependencies
        uses: ./.github/workflows/install-dependencies

      - name: Check TypeScript
        run: yarn ts

      - name: Check ESLint
        run: yarn lint

      - name: Run Unit tests
        run: yarn test
