name: Testapp build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: 1.0.0
        required: true
      build-number:
        description: Build number
        required: true
      extension:
        type: boolean
        description: extension
        default: false
        required: true
      ios:
        type: boolean
        description: iOS
        default: true
        required: true
      android:
        type: boolean
        description: Android
        default: true
        required: true

jobs:
  testapp-build:
    name: Creates extension, iOS & Android builds
    runs-on: macos-latest
    environment: production
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Environment setup
        uses: ./.github/workflows/environment-setup

      - name: Secrets setup
        uses: ./.github/workflows/secrets-setup
        with:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install:all

      - name: Update extension version
        if: ${{ github.event.inputs.extension == 'true' }}
        uses: jossef/action-set-json-field@v2
        with:
          file: apps/extension/public/manifest.json
          field: version
          value: ${{ github.event.inputs.version }}

      - name: Create extension build
        if: ${{ github.event.inputs.extension == 'true' }}
        run: yarn build:extension

      - name: Upload extension artifact
        if: ${{ github.event.inputs.extension == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: chrome
          path: apps/extension/dist
          if-no-files-found: error
          retention-days: 30

      - name: Setup Xcode
        if: ${{ github.event.inputs.ios == 'true' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - name: Update iOS version
        if: ${{ github.event.inputs.ios == 'true' }}
        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
        with:
          info-plist-path: apps/mobile/ios/KlaytnWallet/Info.plist
          bundle-short-version-string: ${{ github.event.inputs.version }}
          bundle-version: ${{ github.event.inputs.build-number }}

      - name: Install Pods
        if: ${{ github.event.inputs.ios == 'true' }}
        run: yarn install:pods

      - name: Build iOS
        if: ${{ github.event.inputs.ios == 'true' }}
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: apps/mobile/ios/KlaytnWallet.xcodeproj
          workspace-path: apps/mobile/ios/KlaytnWallet.xcworkspace
          scheme: KlaytnWallet
          export-method: ad-hoc
          configuration: Release
          output-path: apps/mobile/ios/build/KlaytnWallet.ipa
          p12-base64: ${{ secrets.P12_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.ADHOC_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}

      - name: Upload iOS artifact to TestApp.io
        if: ${{ github.event.inputs.ios == 'true' }}
        uses: testappio/github-action@v5
        with:
          api_token: ${{ secrets.TESTAPPIO_API_TOKEN }}
          app_id: ${{ secrets.TESTAPPIO_APP_ID }}
          file: apps/mobile/ios/build/KlaytnWallet.ipa
          release_notes: ${{env.GIT_BRANCH_NAME}} iOS
          git_release_notes: false
          include_git_commit_id: false
          notify: true

      - name: Update Android version
        if: ${{ github.event.inputs.android == 'true' }}
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: apps/mobile/android/app/build.gradle
          version-name: ${{ github.event.inputs.version }}
          version-code: ${{ github.event.inputs.build-number }}

      - name: Set up JDK 11
        if: ${{ github.event.inputs.android == 'true' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build Android
        if: ${{ github.event.inputs.android == 'true' }}
        run: yarn build:android

      - name: Upload Android artifact to TestApp.io
        if: ${{ github.event.inputs.android == 'true' }}
        uses: testappio/github-action@v5
        with:
          api_token: ${{ secrets.TESTAPPIO_API_TOKEN }}
          app_id: ${{ secrets.TESTAPPIO_APP_ID }}
          file: apps/mobile/android/app/build/outputs/apk/release/app-release.apk
          release_notes: ${{env.GIT_BRANCH_NAME}} Android
          git_release_notes: false
          include_git_commit_id: false
          notify: true
